"""Generate the Cursor configuration from the Claude Code one, so there is a single source.

    uv run python scripts/sync_cursor.py            # write .cursor/
    uv run python scripts/sync_cursor.py --check    # fail if .cursor/ is out of date

Cursor reads AGENTS.md, .claude/skills/ and .claude/agents/ by itself. What it does not read
is CLAUDE.md and .claude/rules/, and its sub-agents take a different `model` value. This
script covers exactly that gap:

    CLAUDE.md               -> .cursor/rules/pair-programming.mdc   (always applied)
    .claude/rules/<x>.md    -> .cursor/rules/<x>.mdc                (always applied)
    .claude/agents/<x>.md   -> .cursor/agents/<x>.md                (model: inherit)
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HEADER = (
    "<!-- Generated by scripts/sync_cursor.py. Edit the source file, then run `make cursor`. -->"
)
AGENTS_IMPORT = "Repository conventions, layout and commands: @AGENTS.md"
AGENTS_POINTER = (
    "Repository conventions, layout and commands are in `AGENTS.md` at the repository root. "
    "Read it before the first change."
)
# Agents that also run commands (e.g. `make check`) are not marked read-only.
READ_ONLY_TOOLS = {"Read", "Grep", "Glob"}


def split_frontmatter(text: str) -> tuple[dict[str, str], str]:
    """Split a markdown file into its simple `key: value` frontmatter and its body."""
    if not text.startswith("---\n"):
        return {}, text
    raw, body = text[4:].split("\n---\n", 1)
    pairs = (line.split(":", 1) for line in raw.splitlines() if ":" in line)
    return {key.strip(): value.strip() for key, value in pairs}, body.lstrip("\n")


def rule(description: str, body: str) -> str:
    return f"---\ndescription: {description}\nalwaysApply: true\n---\n\n{HEADER}\n\n{body}"


def generated_files() -> dict[Path, str]:
    files: dict[Path, str] = {}

    claude_md = (ROOT / "CLAUDE.md").read_text()
    if AGENTS_IMPORT not in claude_md:
        raise SystemExit("CLAUDE.md no longer contains the AGENTS.md import line")
    files[ROOT / ".cursor/rules/pair-programming.mdc"] = rule(
        "How to work in this repository and the trigger phrases",
        claude_md.replace(AGENTS_IMPORT, AGENTS_POINTER),
    )

    for source in sorted((ROOT / ".claude/rules").glob("*.md")):
        title = source.read_text().splitlines()[0].lstrip("# ").strip()
        files[ROOT / f".cursor/rules/{source.stem}.mdc"] = rule(
            f"{title} rules for this repository", source.read_text()
        )

    for source in sorted((ROOT / ".claude/agents").glob("*.md")):
        meta, body = split_frontmatter(source.read_text())
        tools = {tool.strip() for tool in meta.get("tools", "").split(",") if tool.strip()}
        readonly = "true" if tools and tools <= READ_ONLY_TOOLS else "false"
        files[ROOT / f".cursor/agents/{source.name}"] = (
            f"---\nname: {meta['name']}\ndescription: {meta['description']}\n"
            f"model: inherit\nreadonly: {readonly}\n---\n\n{HEADER}\n\n{body}"
        )
    return files


def main() -> int:
    check_only = "--check" in sys.argv[1:]
    expected = generated_files()
    stale = [
        path
        for path, content in expected.items()
        if not path.exists() or path.read_text() != content
    ]
    known = {path for path in expected}
    orphans = [
        path
        for folder in (ROOT / ".cursor/rules", ROOT / ".cursor/agents")
        if folder.exists()
        for path in folder.iterdir()
        if path not in known
    ]

    if check_only:
        for path in [*stale, *orphans]:
            print(f"out of date: {path.relative_to(ROOT)}")
        return 1 if stale or orphans else 0

    for path in orphans:
        path.unlink()
    for path, content in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
    print(f"wrote {len(expected)} files under .cursor/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
